//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FYPBDEntities : DbContext
    {
        public FYPBDEntities()
            : base("name=FYPBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Tbl> Category_Tbl { get; set; }
        public virtual DbSet<Comment_Tbl> Comment_Tbl { get; set; }
        public virtual DbSet<Contactus_Tbl> Contactus_Tbl { get; set; }
        public virtual DbSet<Roles_Tbl> Roles_Tbl { get; set; }
        public virtual DbSet<Users_Tbl> Users_Tbl { get; set; }
        public virtual DbSet<Visual_Tbl> Visual_Tbl { get; set; }
        public virtual DbSet<Posts_Tbl> Posts_Tbl { get; set; }
        public virtual DbSet<Area_Tbl> Area_Tbl { get; set; }
        public virtual DbSet<Designation_Tbl> Designation_Tbl { get; set; }
    }
}
