//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts_Tbl()
        {
            this.Visual_Tbl = new HashSet<Visual_Tbl>();
            this.Contactus_Tbl = new HashSet<Contactus_Tbl>();
            this.Comment_Tbl = new HashSet<Comment_Tbl>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string PostName { get; set; }
        public string Status { get; set; }
        public string PostDate { get; set; }
        public string PostDescription { get; set; }
        public string ApprovalDate { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visual_Tbl> Visual_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactus_Tbl> Contactus_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Tbl> Comment_Tbl { get; set; }
        public virtual Users_Tbl Users_Tbl { get; set; }
        public virtual Area_Tbl Area_Tbl { get; set; }
    }
}
