//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_Tbl()
        {
            this.Comment_Tbl = new HashSet<Comment_Tbl>();
            this.Visual_Tbl = new HashSet<Visual_Tbl>();
            this.Contactus_Tbl = new HashSet<Contactus_Tbl>();
            this.Posts_Tbl = new HashSet<Posts_Tbl>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> RollId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public string CNIC { get; set; }
        public string Password { get; set; }
        public string SignUpDate { get; set; }
        public string ApprovalDate { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual Roles_Tbl Roles_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Tbl> Comment_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visual_Tbl> Visual_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactus_Tbl> Contactus_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts_Tbl> Posts_Tbl { get; set; }
        public virtual Area_Tbl Area_Tbl { get; set; }
        public virtual Designation_Tbl Designation_Tbl { get; set; }
    }
}
